apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-target-prober
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways", "listenersets"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-target-prober
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway-target-prober
subjects:
- kind: ServiceAccount
  name: prober-sa
  namespace: public-ingress-nginx
